// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xduyycigyknioeqyynfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkdXl5Y2lneWtuaW9lcXl5bmZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5OTIwMjcsImV4cCI6MjA1OTU2ODAyN30.8_l0FMbt0THLeERo4nHx7S-gtDbyRHH9H_ZJpYEJRk0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);